"use client";
import { useEffect, useState } from "react";

export default function AdminPage(){
  const [data,setData]=useState<any>(null); const [health,setHealth]=useState<any>(null); const [key,setKey]=useState(""); const [message,setMessage]=useState("");
  const [rateCode,setRateCode]=useState(""); const [rateValue,setRateValue]=useState(0);
  const [overrides,setOverrides]=useState('{\n  "activities": {},\n  "resources": {},\n  "rates": {},\n  "assumptions": {},\n  "additions": {"activities": [], "resources": [], "rates": [], "assumptions": []},\n  "deletions": {"activities": [], "resources": [], "rates": [], "assumptions": []}\n}');
  const [mappingText,setMappingText]=useState("");
  useEffect(()=>{
    fetch('/api/data').then(r=>r.json()).then(setData).catch(()=>setData(null));
    fetch('/api/events/status').then(r=>r.json()).then(setHealth).catch(()=>setHealth(null));
    fetch('/api/admin/ingestion-mappings').then(r=>r.json()).then(x=>setMappingText(JSON.stringify(x,null,2))).catch(()=>{});
  },[]);
  async function save(){setMessage('');try{const body=JSON.parse(overrides);const res=await fetch('/api/admin/save',{method:'POST',headers:{'content-type':'application/json','x-admin-key':key},body:JSON.stringify(body)});const out=await res.json();setMessage(res.ok?`Saved: ${out.saved}`:out.error||'Save failed')}catch(e:any){setMessage(e.message)}}
  async function saveMappings(){setMessage('');try{const body=JSON.parse(mappingText);const res=await fetch('/api/admin/ingestion-mappings',{method:'POST',headers:{'content-type':'application/json','x-admin-key':key},body:JSON.stringify(body)});const out=await res.json();setMessage(res.ok?`Document mappings saved: ${out.path}`:out.error||'Save failed')}catch(e:any){setMessage(e.message)}}
  async function updateRate(){setMessage('');const res=await fetch('/api/orchestrate',{method:'POST',headers:{'content-type':'application/json','x-admin-key':key},body:JSON.stringify({action:'rate.update',input:{code:rateCode,rate:rateValue,actor:'admin-ui'}})});const out=await res.json();setMessage(res.ok?`Rate workflow: ${out.mode}${out.saved===false?' — '+out.message:''}`:out.error||'Rate update failed')}
  return <main className="page"><section className="panel"><span className="tag">Private Admin</span><h1 style={{fontSize:44}}>Data & Intake Governance</h1><p className="lead">Admin controls both the corporate data layer and the front-door extraction rules. PostgreSQL writes are synchronous; downstream recalculation, reporting, scope fan-out and publishing can run through the event broker.</p></section>
  <section className="grid"><div className="metric">Mode<b style={{fontSize:18}}>{data?.mode||'—'}</b></div><div className="metric">PostgreSQL<b style={{fontSize:18}}>{health?.database?.available?'ONLINE':'OPTIONAL/OFF'}</b></div><div className="metric">Redis Broker<b style={{fontSize:18}}>{health?.broker?.available?'ONLINE':'OPTIONAL/OFF'}</b></div><div className="metric">Fallback<b>{data?.availability?.fallback_active?'ACTIVE':'READY'}</b></div></section>
  <section className="panel" style={{marginTop:18}}><h2>Admin Authentication</h2><input className="input" type="password" placeholder="SAMCO_ADMIN_KEY" value={key} onChange={e=>setKey(e.target.value)} style={{width:'100%'}}/>{message&&<p>{message}</p>}</section>
  <section className="panel" style={{marginTop:18}}><h2>Orchestrated Rate Update</h2><p className="muted">When PostgreSQL is configured, this updates the rate immediately, records audit history and creates a durable <code>rate.updated</code> outbox event.</p><div style={{display:'grid',gridTemplateColumns:'1fr 1fr auto',gap:10}}><input className="input" placeholder="Rate code" value={rateCode} onChange={e=>setRateCode(e.target.value)}/><input className="input" type="number" placeholder="Rate" value={rateValue} onChange={e=>setRateValue(Number(e.target.value))}/><button className="button" onClick={updateRate}>Update Rate</button></div></section>
  <section className="panel" style={{marginTop:18}}><div className="section-title-row"><div><h2>Project Intake Mapping Rules</h2><p className="muted">These rules govern document classification, BOQ/keyword/symbol → CSI mapping, contract-term detection and SAM-CTO auto-accept/review thresholds. They are editable by Admin rather than hardcoded into the Python engine.</p></div><div style={{display:'flex',gap:8}}><a className="button secondary" href="/intake">Test Intake</a><a className="button secondary" href="/admin/scope-review">Review SAM-CTO Mappings</a></div></div><textarea className="textarea mapping-editor" value={mappingText} onChange={e=>setMappingText(e.target.value)}/><button className="button" onClick={saveMappings} style={{marginTop:10}}>Save Intake Mapping Rules</button></section>
  <section className="panel" style={{marginTop:18}}><h2>Local Admin Override Editor</h2><p className="muted">Use this for the local/Git-controlled corporate baseline. It survives Excel rebuilds and can change rates, resources, activity fields and controlled <b>SAM-CTO-#########</b> IDs.</p><textarea className="textarea" value={overrides} onChange={e=>setOverrides(e.target.value)}/><div style={{display:'flex',gap:10,marginTop:10}}><button className="button" onClick={save}>Save Local Override</button><button className="button secondary" onClick={()=>location.href='/'}>Return to Hub</button></div></section>
  </main>
}
