"use client";
import { useState } from "react";
export default function ScopeReviewClient({rows}:{rows:any[]}){
  const [key,setKey]=useState(""); const [message,setMessage]=useState(""); const [codes,setCodes]=useState<Record<string,string>>({});
  async function act(id:string,action:"approve"|"reject",suggested?:string){
    const samco=codes[id]||suggested||""; const res=await fetch('/api/scope/review',{method:'POST',headers:{'content-type':'application/json','x-admin-key':key},body:JSON.stringify({id,action,samco_code:samco})}); const out=await res.json(); setMessage(res.ok?`${action} saved for ${id}`:out.error||'Failed'); if(res.ok) location.reload();
  }
  return <><section className="panel" style={{marginTop:18}}><h2>Review Authentication</h2><input className="input" type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="SAMCO_ADMIN_KEY" style={{width:'100%'}}/>{message&&<p>{message}</p>}</section><section className="panel" style={{marginTop:18}}><h2>Mapping Review Queue</h2>{!rows.length?<p className="muted">No review/unmapped entries are persisted.</p>:<div className="table-wrap"><table><thead><tr><th>Project</th><th>CSI / Scope</th><th>Proposed SAM-CTO</th><th>Confidence</th><th>Controlled Decision</th></tr></thead><tbody>{rows.map(r=>{const proposed=r.payload?.samco_candidates?.[0];return <tr key={r.id}><td>{r.project_code}</td><td>{r.csi_code}<br/><span className="tiny">{r.payload?.boq_items?.[0]?.description||r.csi_title}</span></td><td>{proposed?.master_code||"None"}<br/><span className="tiny">{proposed?.title||""}</span></td><td>{Math.round((Number(r.mapping_confidence)||0)*100)}%</td><td><div style={{display:'flex',gap:6,minWidth:360}}><input className="input" value={codes[r.id]??proposed?.master_code??""} onChange={e=>setCodes({...codes,[r.id]:e.target.value})} placeholder="SAM-CTO-#########"/><button className="button" onClick={()=>act(r.id,'approve',proposed?.master_code)}>Approve</button><button className="button secondary" onClick={()=>act(r.id,'reject')}>Reject</button></div></td></tr>})}</tbody></table></div>}</section></>
}
