import { dbHealth } from "@/lib/db";
import { brokerHealth } from "@/lib/events";
import { integrationStatus } from "@/lib/integration-gateway";
export const dynamic="force-dynamic";
export default async function SystemPage(){
  const [db,broker]=await Promise.all([dbHealth(),brokerHealth()]); const integrations=integrationStatus();
  return <main className="page"><section className="panel"><span className="tag">Applied Architecture v0.4</span><h1 style={{fontSize:48}}>Intake → Orchestration → Departments</h1><p className="lead">Project documents now enter through the controlled intake engine before downstream work begins. Core Planning/Tender/Cost functions remain deterministic; PostgreSQL stores governed results; Redis accelerates non-critical fan-out and background work.</p><div className="flow"><span className="node">PDF / DXF</span><span className="arrow">→</span><span className="node">Extract / Classify</span><span className="arrow">→</span><span className="node">CSI</span><span className="arrow">→</span><span className="node">SAM-CTO</span><span className="arrow">→</span><span className="node">PostgreSQL + Outbox</span><span className="arrow">→</span><span className="node">4 Departments</span></div></section>
  <section className="grid"><div className="metric">PostgreSQL<b style={{fontSize:18}}>{db.available?"ONLINE":"OPTIONAL/OFF"}</b></div><div className="metric">Redis Broker<b style={{fontSize:18}}>{broker.available?"ONLINE":"OPTIONAL/OFF"}</b></div><div className="metric">Document Intake<b style={{fontSize:18}}>WIRED</b></div><div className="metric">ML / LLM<b style={{fontSize:18}}>OPTIONAL</b></div></section>
  <section className="hero" style={{marginTop:18}}><div className="panel"><h2>Core Reliability</h2><p className="muted">{db.message}</p><p className="muted">{broker.message}</p><p>Excel/JSON corporate data remains the safe baseline. Document ingestion adds project scope; it does not determine whether the standards, pricing or duration engines can operate.</p></div><div className="panel"><h2>Failure Isolation</h2><p className="muted">OCR unavailable → native/vector evidence still processes and the record is flagged for review. Redis unavailable → PostgreSQL outbox remains durable. Historical/live data unavailable → corporate baseline. ML/LLM unavailable → deterministic rules.</p></div></section>
  <section className="panel" style={{marginTop:18}}><h2>Integration Gateway</h2><table><thead><tr><th>Integration</th><th>Configured</th><th>Required for Corporate Core</th></tr></thead><tbody>{integrations.map(x=><tr key={x.name}><td>{x.name.replaceAll('_',' ')}</td><td>{x.configured?"Yes":"No"}</td><td>No</td></tr>)}</tbody></table></section>
  <section className="panel" style={{marginTop:18}}><h2>Department Fan-Out</h2><div className="department-feed"><div className="feed-card"><b>Technical</b><p>Evidence completeness, specifications, drawing/BOQ conflicts and interfaces.</p></div><div className="feed-card"><b>Tender</b><p>BOQ quantity + SAM-CTO mapping → resources, governed rates and pricing.</p></div><div className="feed-card"><b>Planning</b><p>SAM-CTO activity + quantity → productivity, crews, duration, logic and P6.</p></div><div className="feed-card"><b>Cost Control</b><p>Same scope identity → budget/CBS/actual/EAC mapping.</p></div></div></section></main>
}
